# Generated by Django 4.2.3 on 2023-07-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_is_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.ImageField(blank=True, null=True, upload_to='music/images'),
        ),
    ]
